# DragonFights Configuration 1.1.0
# This config file is dynamic and saved when the server is shutdown.
#
boss-bar:
  #
  # Allows to change default colour for boss bar.
  # Supports values from: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
  colour: GREEN
  # Allows to change default style for the boss bar.
  # Supports values from: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html
  style: SOLID
battle:
  # This option allows to enable dragon fight when player joins the end first time.
  # On first join it will start dragon summoning sequence.
  # Note, this will void blocks to generate exit portal. You should adjust blueprint so there are enough
  # space around the bedrock block for it to spawn.
  start-on-join: false
  # Number of towers generated for the battle.
  # Default value is 12.
  tower-count: 12
  # Number of inner path points for dragon to fly between towers and end trophy generated for the battle.
  # It is recommended to set it to the half of the tower numbers, but never less than 4.
  # Default value is 6. Minimal value is 4.
  inner-path-point-count: 6
  # Distance from portal till the towers.
  # Default value is 40.
  tower-distance: 40
  # Minimal height for the tower.
  # Default value is 120.
  tower-min-height: 120
  # Maximal height for the tower.
  # Default value is 150.
  tower-max-height: 150
  # Number of protected towers.
  # Default value is 2.
  protected-towers: 2
  # Play the battle music.
  # Default value is true.
  play-music: true
  # Set the battle fog.
  # Default value is false.
  enable-fog: false
  # Battle Seed is a semi-random number that generates towers in the end.
  # This allows to give equal arena for each player.
  battle-seed: 0
advancements:
  # Set of advancements that will be granted upon summoning dragon for the first time.
  # This will be granted to all players who is in the end when dragon is summoned.
  # Syntax: <advancement_id>: <criteria>
  # Default value: {}
  summon: {}
  # Set of advancements that will be granted upon resummoning dragon.
  # This will be granted to all players who is in the end when dragon is summoned.
  # Syntax: <advancement_id>: <criteria>
  # Default value:
  # 	minecraft:end/respawn_dragon: summoned_dragon
  resummon:
    minecraft:end/respawn_dragon: summoned_dragon
  # Set of advancements that will be granted upon killing dragon.
  # This will be granted to the player who killed the dragon.
  # Syntax: <advancement_id>: <criteria>
  # Default value:
  # 	minecraft:end/kill_dragon: killed_dragon
  # 	minecraft:adventure/kill_a_mob: minecraft:ender_dragon
  # 	minecraft:adventure/kill_all_mobs: minecraft:ender_dragon
  killer:
    minecraft:adventure/kill_a_mob: minecraft:ender_dragon
    minecraft:end/kill_dragon: killed_dragon
    minecraft:adventure/kill_all_mobs: minecraft:ender_dragon
  # Set of advancements that will be granted upon killing dragon.
  # This will be granted to all players who is in the end when dragon is killed.
  # Syntax: <advancement_id>: <criteria>
  # Default value: {}
  killed: {}
#
# This list stores GameModes in which DragonFights addon should not work.
# To disable addon it is necessary to write its name in new line that starts with -. Example:
# disabled-gamemodes:
#  - BSkyBlock
disabled-gamemodes: []
